version: '3.8'

services:
  # PostgreSQL with pgvector extension for RAG system
  postgres-rag:
    image: pgvector/pgvector:pg15
    container_name: exercise6-postgres
    ports:
      - "5433:5432"  # Using 5433 to avoid conflict with existing PostgreSQL on 5432
    environment:
      - POSTGRES_DB=rag_chatbot
      - POSTGRES_USER=rag_user
      - POSTGRES_PASSWORD=rag_password_2024
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres_rag_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./database/migrations:/docker-entrypoint-initdb.d/migrations
    networks:
      - rag_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rag_user -d rag_chatbot"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # ChromaDB for vector similarity search
  chromadb:
    image: chromadb/chroma:latest
    container_name: exercise6-chromadb
    ports:
      - "8000:8000"  # ChromaDB default port
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - PERSIST_DIRECTORY=/chroma/data
      - ANONYMIZED_TELEMETRY=False
    volumes:
      - chromadb_data:/chroma/data
    networks:
      - rag_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Redis for caching (optional but recommended for production)
  redis-rag:
    image: redis:7-alpine
    container_name: exercise6-redis
    ports:
      - "6380:6379"  # Using 6380 to avoid conflict with existing Redis on 6379
    command: redis-server --appendonly yes --requirepass rag_redis_2024
    volumes:
      - redis_rag_data:/data
    networks:
      - rag_network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: exercise6-backend
    ports:
      - "8002:8000"  # Using 8002 to avoid conflicts
    environment:
      - DATABASE_URL=postgresql://rag_user:rag_password_2024@postgres-rag:5432/rag_chatbot
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
      - REDIS_URL=redis://rag_redis_2024@redis-rag:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - CORS_ORIGINS=http://localhost:3002,http://localhost:3003
      - MAX_FILE_SIZE=50MB
      - CHUNK_SIZE=1000
      - CHUNK_OVERLAP=200
    volumes:
      - ./backend:/app
      - uploaded_files:/app/uploads
    networks:
      - rag_network
    depends_on:
      postgres-rag:
        condition: service_healthy
      chromadb:
        condition: service_healthy
      redis-rag:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
        - action: rebuild
          path: ./backend/requirements.txt

  # Frontend (Unified Next.js App with Admin Console and Chat Interface)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: exercise6-frontend
    ports:
      - "3002:3000"  # Frontend on port 3002
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8002
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - rag_network
    depends_on:
      - backend
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: ./frontend/package.json

  # Nginx reverse proxy (optional, for production)
  nginx:
    image: nginx:alpine
    container_name: exercise6-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - rag_network
    depends_on:
      - backend
      - admin-frontend
      - chat-frontend
    restart: unless-stopped
    profiles:
      - production

networks:
  rag_network:
    driver: bridge
    name: exercise6_rag_network

volumes:
  postgres_rag_data:
    name: exercise6_postgres_data
  chromadb_data:
    name: exercise6_chromadb_data
  redis_rag_data:
    name: exercise6_redis_data
  uploaded_files:
    name: exercise6_uploaded_files
